baseURL = "https://nataliaacosta.com/"
languageCode = "es-mx"
title = "Natalia Acosta"
theme = "personal-web"
copyright="© Natalia Acosta"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hola, Soy Natalia Acosta"
  sub = "UX/UI Designer"

[params.main]
  latestPublishHeader = "Mis proyectos"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519" 
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Uy! Parece que hubo un problema :('
  p = "Parace que la página que buscas no existe"

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/stat_one.jpg' # Imagen de fondo de la barra lateral  (En este momento, la foto de las nubes), poner la ruta de la imagen -
  # - que se quiera poner relativa a la ruta del proyecto 
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/CV_Profile.jpeg" # Ruta de la foto de perfil 
[params.assets]
  favicon = "/images/LOGO STUDIO (2).png"
  customCSS = ""

[params.social]
  github = "https://github.com/nataliarodcost"
  # twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/natalia-acosta-rodr%C3%ADguez-15b3b9238/"
  # medium = "https://medium.com/"
  # codepen = "https://codepen.io/"
  # facebook = "https://www.facebook.com/"
  # youtube = "https://www.youtube.com/"
  instagram = "https://www.instagram.com/nataliarodcost/"
  # gitlab = "https://gitlab.com/"
  # keybase = "https://keybase.io/"
  whatsapp = "https://wa.me/524646518616"

[params.contact]
  email = "natalia.acosta.rdz@gmail.com"
  text= "Contactame " # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

# [[menu.main]]
#   identifier = "blog"
#   name = "Post"
#   title = "Blog section"
#   url = "/post/"
#   weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true